blog/urls.py
from .views import *
from django.urls import path
from blog.feeds import LatestEntriesFeed

app_name="blog"
urlpatterns= [
            path('',blog_home,name='blog_home'),
            path('single',blog_single,name='blog_single'),
            path('<int:pid>',blog_single,name='single'),
            path('category/<str:cat_name>',blog_home,name='category'),
            path('author/<str:author_name>',blog_home,name='author'),
            path('search/',blog_search,name='search'),
            path('rss/feed/', LatestEntriesFeed()),    
]

mysite1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include, re_path
from .views import *
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth import views as auth_views

sitemaps={'static':StaticViewSitemap,'blog':BlogSitemap,}

app_name="mysite1"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('elements/',elements,name='elements'),
    path('contact/',contact,name='contact'),
    path('blog/',include('blog.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path('accounts/', include('allauth.urls')),
    # re_path(r"^.*",maintenance),
    re_path(r'^password-reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password-reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^password-reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name

# Create your models here.
class Post(models.Model):
    image=models.ImageField(upload_to='blog/',default='blog/def.jpg')
    author=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title=models.CharField(max_length=255)
    content=models.TextField()
    #tags
    category=models.ManyToManyField(Category)
    counted_views=models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject=models.CharField(max_length=255)
    message = models.TextField()
    approved=models.BooleanField(default=False)
    created_date=models.DateTimeField(auto_now_add = True)
    updated_date=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

class Contact(models.Model):
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject=models.CharField(max_length=255)
    message=models.TextField()
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment,Contact

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['post','name','email','subject','message']

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields=['name','email','subject','message']

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import Post,Comment
from blog.forms import CommentForm
# Create your views here.


def blog_home(request,cat_name=None,author_name=None):
    posts=Post.objects.filter(status=1)
    if cat_name:
        posts=posts.filter(category__name=cat_name)
    if author_name:
        posts=posts.filter(author__username=author_name)
    posts=Paginator(posts,3)
    try:
        page_number=request.GET.get('page')
        posts=posts.get_page(page_number)
    except EmptyPage and PageNotAnInteger:
        posts=posts.get_page(1)

    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)

def blog_single(request,pid):
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            form.save()
            # message.add_message(request,message.SUCCESS,'aqa shod')
        # else:
            # message.add_message(request,message.ERROR,'aqa nashod')
    form=CommentForm()
    post=get_object_or_404(Post,id=pid,status=1)
    comments=Comment.objects.filter(post=post.id,approved=True).order_by('-created_date')
    context={'post':post,'comments':comments,'form':form}
    return render(request,'blog/blog-single.html',context)

def blog_search(request):
    posts=Post.objects.filter(status=1)
    if request.method == 'GET':
        posts=posts.filter(content__contains=request.GET.get('s'))
    context = {'posts':posts}
    return render (request,'blog/blog-home.html',context)

mysite1/views.py
from django.shortcuts import render
from blog.forms import ContactForm



def index(request):
    return render(request,'index.html')

def about(request):
    return render(request,'about.html')

def elements(request):
    return render(request,'elements.html')

def contact(request):
    if request.method == 'POST':
        form=ContactForm(request.POST)
        if form.is_valid():
            form.save()
    form=ContactForm()
    return render(request,'contact.html',{'form':form})

# def maintenance(request):
#     return render(request,'maintenance.html')

templates/about.html
	<!DOCTYPE html>
	{%extends 'base.html'%}
	{%load static%}
	{% block title %}about our website{% endblock title %}
	{%block content%}

			<!-- start banner Area -->
			<section class="about-banner relative">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								About Us
							</h1>
							<p class="text-white link-nav"><a href="{%url 'index'%}">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="about.html"> About Us</a></p>
						</div>
					</div>
				</div>
			</section>
			<!-- End banner Area -->

			<!-- Start about-info Area -->
			<section class="about-info-area section-gap">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6 info-left">
							<img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="">
						</div>
						<div class="col-lg-6 info-right">
							<h6>About Us</h6>
							<h1>Who We Are?</h1>
							<p>
								Here, I focus on a range of items and features that we use in life without giving them a second thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.
							</p>
						</div>
					</div>
				</div>
			</section>
			<!-- End about-info Area -->

			<!-- Start other-issue Area -->
			<section class="other-issue-area section-gap">
				<div class="container">
		            <div class="row d-flex justify-content-center">
		                <div class="menu-content pb-70 col-lg-9">
		                    <div class="title text-center">
		                        <h1 class="mb-10">Other issues we can help you with</h1>
		                        <p>We all live in an age that belongs to the young at heart. Life that is.</p>
		                    </div>
		                </div>
		            </div>
					<div class="row">
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>Rent a Car</h4>
								</a>
								<p>
									The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>Cruise Booking</h4>
								</a>
								<p>
									I was always somebody who felt quite sorry for myself, what I had not got compared.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>To Do List</h4>
								</a>
								<p>
									The following article covers a topic that has recently moved to center stage–at least it seems.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>Food Features</h4>
								</a>
								<p>
									There are many kinds of narratives and organizing principles. Science is driven by evidence.
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End other-issue Area -->

{%endblock%}

templates/blog/blog-category.html
{%load static%}

{% block title %}category{% endblock title %}

<div class="single-sidebar-widget post-category-widget">
  <h4 class="category-title">Post Catgories</h4>
  <ul class="cat-list">

    {%for name,count in categories.items%}
    <li>
      <a href="{%url 'blog:category' cat_name=name%}" class="d-flex justify-content-between">
        <p>{{name}}</p>
        <p>{{count}}</p>
      </a>
    </li>
    {%endfor%}
  </ul>
</div>

templates/blog/blog-home.html
	<!DOCTYPE html>
	{%extends 'base.html'%}
	{%load static%}
	{%load blog-tags%}
	{% block title %}our awesome travel blog{% endblock title %}

	{%block content%}
	

			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						<div itemscope itemtype="https://schema.org/astrology class="about-content blog-header-content col-lg-12">
							<h2 class="text-white">
								Dude You’re Getting
								a Telescope
							</h2>
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>
						</div>
					</div>
				</div>
			</section>
			<!-- End banner Area -->

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="Enjoy your social life together">
								  	  </div>
								      <div itemscope itemtype="https://schema.org/social class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="Be a part of politics">
								  	  </div>
								      <div itemscope itemtype="https://schema.org/politics class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="Let the food be finished">
								  	  </div>
								      <div itemscope itemtype="https://schema.org/food class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End top-category-widget Area -->

			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">


							{%for post in posts%}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{%for cat in post.category.all%}
										<li><a href="{%url 'blog:category' cat_name=cat.name%}">{{cat.name}}</a></li>
										{%if not forloop.last%}
										,
										{%endif%}
										{%endfor%}
									</ul>
									<div  itemscope itemprop="author"  itemtype="https://schema.org/comment class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{%url 'blog:author' author_name=post.author%}">{{post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="this post has no image">
									</div>
									<a class="posts-title" href="{%url 'blog:single' pid=post.id%}"><h2>{{post.title}}</h2></a>
									<p class="excert">
										{{post.content|truncatewords_html:5|safe}}
									</p>
									<a href="{%url 'blog:single' pid=post.id%}" class="primary-btn">View More</a>
								</div>
							</div>
							{%endfor%}




		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
															{%if posts.has_previous%}
		                            <li class="page-item">
		                                <a href="?page={{posts.previous_page_number}}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
																{%endif%}


																{%for i in posts.paginator.page_range%}
																	{%if posts.number == i%}
			                            <li class="page-item active"  ><a href="?page={{i}}" class="page-link">{{i}}</a></li>
																	{%else%}
																	<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
																	{%endif%}
		                            {%endfor%}



																{%if posts.has_next%}
		                            <li class="page-item">
		                                <a href="?page={{posts.next_page_number}}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
																{%endif%}
		                        </ul>
		                    </nav>



						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">

								{%include 'blog/blog-search.html'%}

								<div itemscope itemtype="https://schema.org/author class="single-sidebar-widget user-info-widget">
									<img src="{% static 'img/blog/user-info.png' %}" alt="author has no picture">
									<a href="#"><h4>Charlie Barber</h4></a>
									<p>
										Senior blog writer
									</p>
									<ul class="social-links">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-github"></i></a></li>
										<li><a href="#"><i class="fa fa-behance"></i></a></li>
									</ul>
									<p>
										Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
									</p>
								</div>



								{%latestpost%}


								<div class="single-sidebar-widget ads-widget">
									<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt="sorry! no image"></a>
								</div>


								{%postcategories%}

								<div itemscope itemtype="https://schema.org/newsletter class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>
								</div>
								<div itemscope itemtype="https://schema.org/tags itemtype="https://schema.org/Movieclass="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Architecture</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Art</a></li>
										<li><a href="#">Adventure</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Adventure</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End post-content Area -->

{%endblock%}

templates/blog/blog-latestpost.html
{%load static%}
{% block title %}latest post of blog{% endblock title %}
<div class="single-sidebar-widget popular-post-widget">
  <h4 class="popular-title">Latest Posts</h4>
  <div class="popular-post-list">
    {%for post in latestpost%}
    <div class="single-post-list d-flex flex-row align-items-center">
      <div class="thumb">
        <img class="img-fluid" src="{{post.image.url}}" alt="">
      </div>
      <div class="details">
        <a href="{%url 'blog:single' pid=post.id%}"><h6>{{post.title}}</h6></a>
        <p>{{post.published_date|date:"D d M Y"}}</p>
      </div>
    </div>
{%endfor%}


  </div>
</div>

templates/blog/blog-search.html
{%load static%}
{% block title %}search{% endblock title %}
<div class="single-sidebar-widget search-widget">
  <form class="search-form" action="{%url 'blog:search'%}" method="get">
    <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
</div>

templates/blog/blog-single.html
	<!DOCTYPE html>
	{%extends 'base.html'%}
	{%load static%}
	{% block title %}blog description page{% endblock title %}
	{%block content%}
	{%load blog-tags%}
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div itemscope class="feature-img">
										<img class="img-fluid" itemprop="url" src="{{post.image.url}}" alt="no image is available">
									</div>
								</div>
								<div itemscope itemprop="author" itemtype="https://schema.org/category class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{%for cat in post.category.all%}
										<li><a href="{%url 'blog:category' cat_name=cat.name%}">{{cat.name}}</a></li>
										{%if not forloop.last%}
										,
										{%endif%}
										{%endfor%}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{%url 'blog:author' author_name=post.author%}">{{post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{post.title}}</h3>
									<p class="excert">
										{{post.content|safe}}
									</p>

								</div>
								<div class="col-lg-12">


								</div>
							</div>

							<div class="navigation-area">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										<div class="thumb">
											<a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg' %}" alt="previous"></a>
										</div>
										<div class="arrow">
											<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
										</div>
										<div itemscope class="detials">
											<p>Prev Post</p>
											<a href="#"><h4>Space The Final Frontier</h4></a>
										</div>
									</div>
									<div itemscope itemtype="https://schema.org/astrology class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										<div class="detials">
											<p>Next Post</p>
											<a href="#"><h4>Telescopes 101</h4></a>
										</div>
										<div class="arrow">
											<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
										</div>
										<div class="thumb">
											<a href="#"><img class="img-fluid" src="{% static 'img/blog/next.jpg' %}" alt="next"></a>
										</div>
									</div>
								</div>
							</div>
							<div class="comments-area">
								<h4>{{comments|length}}  Comments</h4>


								{%for comment in comments%}
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c1.jpg' %}" alt="comment">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{comment.name}}</a></h5>
                                                <p class="date">{{comment.created_date}}</p>
                                                <p class="comment">
                                                    {{comment.message}}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a>
                                        </div>
                                    </div>
                                </div>
																{%endfor%}



							</div>
							
							<div class="comment-form">
								<h4>Leave a Comment</h4>


								<form method="post" action='{%url "blog:single" pid=post.id%}'>
									{% csrf_token %}
									<div class="form-group form-inline">

									    <input type="hidden" class="form-control" name="post" value="{{post.id}}">

									  <div class="form-group col-lg-6 col-md-12 name">
									    <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>
									</div>
									<div class="form-group">
										<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									</div>
									<div class="form-group">
										<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									</div>
									<button type="submit" name="button" class="primary-btn text-uppercase">Post Comment</button>
								</form>



							</div>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">

								{%include 'blog/blog-search.html'%}


								<div class="single-sidebar-widget user-info-widget">
									<img src="img/blog/user-info.png" alt="authors picture">
									<a href="#"><h4>Charlie Barber</h4></a>
									<p>
										Senior blog writer
									</p>
									<ul class="social-links">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-github"></i></a></li>
										<li><a href="#"><i class="fa fa-behance"></i></a></li>
									</ul>
									<p>
										Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
									</p>
								</div>

								{%latestpost%}

								<div class="single-sidebar-widget ads-widget">
									<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt="best place for advertise"></a>
								</div>


								{%postcategories%}


								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>
								</div>
								<div itemscope itemtype="https://schema.org/tags class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Architecture</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Art</a></li>
										<li><a href="#">Adventure</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Adventure</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End post-content Area -->

{%endblock%}